name: example_cli
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  jpegtran_ffi:
    path: ../

dev_dependencies:
  lints: ^1.0.0
